/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatutRouteImport } from './routes/statut'
import { Route as ScrutinsRouteImport } from './routes/scrutins'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as Legislature16RouteImport } from './routes/legislature-16'
import { Route as GroupesRouteImport } from './routes/groupes'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DeputesRouteImport } from './routes/deputes'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ScrutinNumeroRouteImport } from './routes/scrutin.$numero'
import { Route as GroupesSigleRouteImport } from './routes/groupes.$sigle'
import { Route as DeputeSlugRouteImport } from './routes/depute.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiMetaRouteImport } from './routes/api/meta'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1ScrutinsRouteImport } from './routes/api/v1/scrutins'
import { Route as ApiV1GroupesRouteImport } from './routes/api/v1/groupes'
import { Route as ApiV1DeputesRouteImport } from './routes/api/v1/deputes'
import { Route as ApiV1ScrutinsNumeroRouteImport } from './routes/api/v1/scrutins.$numero'
import { Route as ApiV1KeysCreateRouteImport } from './routes/api/v1/keys/create'

const StatutRoute = StatutRouteImport.update({
  id: '/statut',
  path: '/statut',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrutinsRoute = ScrutinsRouteImport.update({
  id: '/scrutins',
  path: '/scrutins',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const Legislature16Route = Legislature16RouteImport.update({
  id: '/legislature-16',
  path: '/legislature-16',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesRoute = GroupesRouteImport.update({
  id: '/groupes',
  path: '/groupes',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputesRoute = DeputesRouteImport.update({
  id: '/deputes',
  path: '/deputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ScrutinNumeroRoute = ScrutinNumeroRouteImport.update({
  id: '/scrutin/$numero',
  path: '/scrutin/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesSigleRoute = GroupesSigleRouteImport.update({
  id: '/$sigle',
  path: '/$sigle',
  getParentRoute: () => GroupesRoute,
} as any)
const DeputeSlugRoute = DeputeSlugRouteImport.update({
  id: '/depute/$slug',
  path: '/depute/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaRoute = ApiMetaRouteImport.update({
  id: '/api/meta',
  path: '/api/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScrutinsRoute = ApiV1ScrutinsRouteImport.update({
  id: '/api/v1/scrutins',
  path: '/api/v1/scrutins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GroupesRoute = ApiV1GroupesRouteImport.update({
  id: '/api/v1/groupes',
  path: '/api/v1/groupes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeputesRoute = ApiV1DeputesRouteImport.update({
  id: '/api/v1/deputes',
  path: '/api/v1/deputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScrutinsNumeroRoute = ApiV1ScrutinsNumeroRouteImport.update({
  id: '/$numero',
  path: '/$numero',
  getParentRoute: () => ApiV1ScrutinsRoute,
} as any)
const ApiV1KeysCreateRoute = ApiV1KeysCreateRouteImport.update({
  id: '/api/v1/keys/create',
  path: '/api/v1/keys/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/developers': typeof DevelopersRoute
  '/groupes': typeof GroupesRouteWithChildren
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/statut': typeof StatutRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/status': typeof ApiStatusRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/groupes/$sigle': typeof GroupesSigleRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog/': typeof BlogIndexRoute
  '/api/v1/deputes': typeof ApiV1DeputesRoute
  '/api/v1/groupes': typeof ApiV1GroupesRoute
  '/api/v1/scrutins': typeof ApiV1ScrutinsRouteWithChildren
  '/api/v1/': typeof ApiV1IndexRoute
  '/api/v1/keys/create': typeof ApiV1KeysCreateRoute
  '/api/v1/scrutins/$numero': typeof ApiV1ScrutinsNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/developers': typeof DevelopersRoute
  '/groupes': typeof GroupesRouteWithChildren
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/statut': typeof StatutRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/status': typeof ApiStatusRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/groupes/$sigle': typeof GroupesSigleRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog': typeof BlogIndexRoute
  '/api/v1/deputes': typeof ApiV1DeputesRoute
  '/api/v1/groupes': typeof ApiV1GroupesRoute
  '/api/v1/scrutins': typeof ApiV1ScrutinsRouteWithChildren
  '/api/v1': typeof ApiV1IndexRoute
  '/api/v1/keys/create': typeof ApiV1KeysCreateRoute
  '/api/v1/scrutins/$numero': typeof ApiV1ScrutinsNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/developers': typeof DevelopersRoute
  '/groupes': typeof GroupesRouteWithChildren
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/statut': typeof StatutRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/status': typeof ApiStatusRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/groupes/$sigle': typeof GroupesSigleRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog/': typeof BlogIndexRoute
  '/api/v1/deputes': typeof ApiV1DeputesRoute
  '/api/v1/groupes': typeof ApiV1GroupesRoute
  '/api/v1/scrutins': typeof ApiV1ScrutinsRouteWithChildren
  '/api/v1/': typeof ApiV1IndexRoute
  '/api/v1/keys/create': typeof ApiV1KeysCreateRoute
  '/api/v1/scrutins/$numero': typeof ApiV1ScrutinsNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/confidentialite'
    | '/deputes'
    | '/developers'
    | '/groupes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/statut'
    | '/api/ai-chat'
    | '/api/meta'
    | '/api/status'
    | '/api/subscribe'
    | '/api/unsubscribe'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/groupes/$sigle'
    | '/scrutin/$numero'
    | '/blog/'
    | '/api/v1/deputes'
    | '/api/v1/groupes'
    | '/api/v1/scrutins'
    | '/api/v1/'
    | '/api/v1/keys/create'
    | '/api/v1/scrutins/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/deputes'
    | '/developers'
    | '/groupes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/statut'
    | '/api/ai-chat'
    | '/api/meta'
    | '/api/status'
    | '/api/subscribe'
    | '/api/unsubscribe'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/groupes/$sigle'
    | '/scrutin/$numero'
    | '/blog'
    | '/api/v1/deputes'
    | '/api/v1/groupes'
    | '/api/v1/scrutins'
    | '/api/v1'
    | '/api/v1/keys/create'
    | '/api/v1/scrutins/$numero'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/blog'
    | '/confidentialite'
    | '/deputes'
    | '/developers'
    | '/groupes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/statut'
    | '/api/ai-chat'
    | '/api/meta'
    | '/api/status'
    | '/api/subscribe'
    | '/api/unsubscribe'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/groupes/$sigle'
    | '/scrutin/$numero'
    | '/blog/'
    | '/api/v1/deputes'
    | '/api/v1/groupes'
    | '/api/v1/scrutins'
    | '/api/v1/'
    | '/api/v1/keys/create'
    | '/api/v1/scrutins/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DeputesRoute: typeof DeputesRoute
  DevelopersRoute: typeof DevelopersRoute
  GroupesRoute: typeof GroupesRouteWithChildren
  Legislature16Route: typeof Legislature16Route
  RechercheRoute: typeof RechercheRoute
  ScrutinsRoute: typeof ScrutinsRoute
  StatutRoute: typeof StatutRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiMetaRoute: typeof ApiMetaRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  ApiVisitsRoute: typeof ApiVisitsRoute
  DeputeSlugRoute: typeof DeputeSlugRoute
  ScrutinNumeroRoute: typeof ScrutinNumeroRoute
  ApiV1DeputesRoute: typeof ApiV1DeputesRoute
  ApiV1GroupesRoute: typeof ApiV1GroupesRoute
  ApiV1ScrutinsRoute: typeof ApiV1ScrutinsRouteWithChildren
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiV1KeysCreateRoute: typeof ApiV1KeysCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statut': {
      id: '/statut'
      path: '/statut'
      fullPath: '/statut'
      preLoaderRoute: typeof StatutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrutins': {
      id: '/scrutins'
      path: '/scrutins'
      fullPath: '/scrutins'
      preLoaderRoute: typeof ScrutinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislature-16': {
      id: '/legislature-16'
      path: '/legislature-16'
      fullPath: '/legislature-16'
      preLoaderRoute: typeof Legislature16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes': {
      id: '/groupes'
      path: '/groupes'
      fullPath: '/groupes'
      preLoaderRoute: typeof GroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputes': {
      id: '/deputes'
      path: '/deputes'
      fullPath: '/deputes'
      preLoaderRoute: typeof DeputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/scrutin/$numero': {
      id: '/scrutin/$numero'
      path: '/scrutin/$numero'
      fullPath: '/scrutin/$numero'
      preLoaderRoute: typeof ScrutinNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes/$sigle': {
      id: '/groupes/$sigle'
      path: '/$sigle'
      fullPath: '/groupes/$sigle'
      preLoaderRoute: typeof GroupesSigleRouteImport
      parentRoute: typeof GroupesRoute
    }
    '/depute/$slug': {
      id: '/depute/$slug'
      path: '/depute/$slug'
      fullPath: '/depute/$slug'
      preLoaderRoute: typeof DeputeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta': {
      id: '/api/meta'
      path: '/api/meta'
      fullPath: '/api/meta'
      preLoaderRoute: typeof ApiMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scrutins': {
      id: '/api/v1/scrutins'
      path: '/api/v1/scrutins'
      fullPath: '/api/v1/scrutins'
      preLoaderRoute: typeof ApiV1ScrutinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/groupes': {
      id: '/api/v1/groupes'
      path: '/api/v1/groupes'
      fullPath: '/api/v1/groupes'
      preLoaderRoute: typeof ApiV1GroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deputes': {
      id: '/api/v1/deputes'
      path: '/api/v1/deputes'
      fullPath: '/api/v1/deputes'
      preLoaderRoute: typeof ApiV1DeputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scrutins/$numero': {
      id: '/api/v1/scrutins/$numero'
      path: '/$numero'
      fullPath: '/api/v1/scrutins/$numero'
      preLoaderRoute: typeof ApiV1ScrutinsNumeroRouteImport
      parentRoute: typeof ApiV1ScrutinsRoute
    }
    '/api/v1/keys/create': {
      id: '/api/v1/keys/create'
      path: '/api/v1/keys/create'
      fullPath: '/api/v1/keys/create'
      preLoaderRoute: typeof ApiV1KeysCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GroupesRouteChildren {
  GroupesSigleRoute: typeof GroupesSigleRoute
}

const GroupesRouteChildren: GroupesRouteChildren = {
  GroupesSigleRoute: GroupesSigleRoute,
}

const GroupesRouteWithChildren =
  GroupesRoute._addFileChildren(GroupesRouteChildren)

interface ApiV1ScrutinsRouteChildren {
  ApiV1ScrutinsNumeroRoute: typeof ApiV1ScrutinsNumeroRoute
}

const ApiV1ScrutinsRouteChildren: ApiV1ScrutinsRouteChildren = {
  ApiV1ScrutinsNumeroRoute: ApiV1ScrutinsNumeroRoute,
}

const ApiV1ScrutinsRouteWithChildren = ApiV1ScrutinsRoute._addFileChildren(
  ApiV1ScrutinsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DeputesRoute: DeputesRoute,
  DevelopersRoute: DevelopersRoute,
  GroupesRoute: GroupesRouteWithChildren,
  Legislature16Route: Legislature16Route,
  RechercheRoute: RechercheRoute,
  ScrutinsRoute: ScrutinsRoute,
  StatutRoute: StatutRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiMetaRoute: ApiMetaRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  ApiVisitsRoute: ApiVisitsRoute,
  DeputeSlugRoute: DeputeSlugRoute,
  ScrutinNumeroRoute: ScrutinNumeroRoute,
  ApiV1DeputesRoute: ApiV1DeputesRoute,
  ApiV1GroupesRoute: ApiV1GroupesRoute,
  ApiV1ScrutinsRoute: ApiV1ScrutinsRouteWithChildren,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiV1KeysCreateRoute: ApiV1KeysCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
