/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatutRouteImport } from './routes/statut'
import { Route as ScrutinsRouteImport } from './routes/scrutins'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as Legislature16RouteImport } from './routes/legislature-16'
import { Route as GroupesRouteImport } from './routes/groupes'
import { Route as DeputesRouteImport } from './routes/deputes'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ScrutinNumeroRouteImport } from './routes/scrutin.$numero'
import { Route as GroupesSigleRouteImport } from './routes/groupes.$sigle'
import { Route as DeputeSlugRouteImport } from './routes/depute.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiMetaRouteImport } from './routes/api/meta'

const StatutRoute = StatutRouteImport.update({
  id: '/statut',
  path: '/statut',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrutinsRoute = ScrutinsRouteImport.update({
  id: '/scrutins',
  path: '/scrutins',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const Legislature16Route = Legislature16RouteImport.update({
  id: '/legislature-16',
  path: '/legislature-16',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesRoute = GroupesRouteImport.update({
  id: '/groupes',
  path: '/groupes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputesRoute = DeputesRouteImport.update({
  id: '/deputes',
  path: '/deputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ScrutinNumeroRoute = ScrutinNumeroRouteImport.update({
  id: '/scrutin/$numero',
  path: '/scrutin/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesSigleRoute = GroupesSigleRouteImport.update({
  id: '/$sigle',
  path: '/$sigle',
  getParentRoute: () => GroupesRoute,
} as any)
const DeputeSlugRoute = DeputeSlugRouteImport.update({
  id: '/depute/$slug',
  path: '/depute/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaRoute = ApiMetaRouteImport.update({
  id: '/api/meta',
  path: '/api/meta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/groupes': typeof GroupesRouteWithChildren
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/statut': typeof StatutRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/status': typeof ApiStatusRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/groupes/$sigle': typeof GroupesSigleRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/groupes': typeof GroupesRouteWithChildren
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/statut': typeof StatutRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/status': typeof ApiStatusRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/groupes/$sigle': typeof GroupesSigleRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/groupes': typeof GroupesRouteWithChildren
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/statut': typeof StatutRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/status': typeof ApiStatusRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/groupes/$sigle': typeof GroupesSigleRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/confidentialite'
    | '/deputes'
    | '/groupes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/statut'
    | '/api/meta'
    | '/api/status'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/groupes/$sigle'
    | '/scrutin/$numero'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/confidentialite'
    | '/deputes'
    | '/groupes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/statut'
    | '/api/meta'
    | '/api/status'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/groupes/$sigle'
    | '/scrutin/$numero'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/blog'
    | '/confidentialite'
    | '/deputes'
    | '/groupes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/statut'
    | '/api/meta'
    | '/api/status'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/groupes/$sigle'
    | '/scrutin/$numero'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DeputesRoute: typeof DeputesRoute
  GroupesRoute: typeof GroupesRouteWithChildren
  Legislature16Route: typeof Legislature16Route
  RechercheRoute: typeof RechercheRoute
  ScrutinsRoute: typeof ScrutinsRoute
  StatutRoute: typeof StatutRoute
  ApiMetaRoute: typeof ApiMetaRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiVisitsRoute: typeof ApiVisitsRoute
  DeputeSlugRoute: typeof DeputeSlugRoute
  ScrutinNumeroRoute: typeof ScrutinNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statut': {
      id: '/statut'
      path: '/statut'
      fullPath: '/statut'
      preLoaderRoute: typeof StatutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrutins': {
      id: '/scrutins'
      path: '/scrutins'
      fullPath: '/scrutins'
      preLoaderRoute: typeof ScrutinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislature-16': {
      id: '/legislature-16'
      path: '/legislature-16'
      fullPath: '/legislature-16'
      preLoaderRoute: typeof Legislature16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes': {
      id: '/groupes'
      path: '/groupes'
      fullPath: '/groupes'
      preLoaderRoute: typeof GroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputes': {
      id: '/deputes'
      path: '/deputes'
      fullPath: '/deputes'
      preLoaderRoute: typeof DeputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/scrutin/$numero': {
      id: '/scrutin/$numero'
      path: '/scrutin/$numero'
      fullPath: '/scrutin/$numero'
      preLoaderRoute: typeof ScrutinNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes/$sigle': {
      id: '/groupes/$sigle'
      path: '/$sigle'
      fullPath: '/groupes/$sigle'
      preLoaderRoute: typeof GroupesSigleRouteImport
      parentRoute: typeof GroupesRoute
    }
    '/depute/$slug': {
      id: '/depute/$slug'
      path: '/depute/$slug'
      fullPath: '/depute/$slug'
      preLoaderRoute: typeof DeputeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta': {
      id: '/api/meta'
      path: '/api/meta'
      fullPath: '/api/meta'
      preLoaderRoute: typeof ApiMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GroupesRouteChildren {
  GroupesSigleRoute: typeof GroupesSigleRoute
}

const GroupesRouteChildren: GroupesRouteChildren = {
  GroupesSigleRoute: GroupesSigleRoute,
}

const GroupesRouteWithChildren =
  GroupesRoute._addFileChildren(GroupesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DeputesRoute: DeputesRoute,
  GroupesRoute: GroupesRouteWithChildren,
  Legislature16Route: Legislature16Route,
  RechercheRoute: RechercheRoute,
  ScrutinsRoute: ScrutinsRoute,
  StatutRoute: StatutRoute,
  ApiMetaRoute: ApiMetaRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiVisitsRoute: ApiVisitsRoute,
  DeputeSlugRoute: DeputeSlugRoute,
  ScrutinNumeroRoute: ScrutinNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
