/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrutinsRouteImport } from './routes/scrutins'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as Legislature16RouteImport } from './routes/legislature-16'
import { Route as DeputesRouteImport } from './routes/deputes'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommencerRouteImport } from './routes/commencer'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ScrutinNumeroRouteImport } from './routes/scrutin.$numero'
import { Route as DeputeSlugRouteImport } from './routes/depute.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'

const ScrutinsRoute = ScrutinsRouteImport.update({
  id: '/scrutins',
  path: '/scrutins',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const Legislature16Route = Legislature16RouteImport.update({
  id: '/legislature-16',
  path: '/legislature-16',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputesRoute = DeputesRouteImport.update({
  id: '/deputes',
  path: '/deputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommencerRoute = CommencerRouteImport.update({
  id: '/commencer',
  path: '/commencer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ScrutinNumeroRoute = ScrutinNumeroRouteImport.update({
  id: '/scrutin/$numero',
  path: '/scrutin/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputeSlugRoute = DeputeSlugRouteImport.update({
  id: '/depute/$slug',
  path: '/depute/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/deputes': typeof DeputesRoute
  '/legislature-16': typeof Legislature16Route
  '/recherche': typeof RechercheRoute
  '/scrutins': typeof ScrutinsRoute
  '/api/visits': typeof ApiVisitsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/depute/$slug': typeof DeputeSlugRoute
  '/scrutin/$numero': typeof ScrutinNumeroRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/commencer'
    | '/confidentialite'
    | '/deputes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/scrutin/$numero'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commencer'
    | '/confidentialite'
    | '/deputes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/scrutin/$numero'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/commencer'
    | '/confidentialite'
    | '/deputes'
    | '/legislature-16'
    | '/recherche'
    | '/scrutins'
    | '/api/visits'
    | '/blog/$slug'
    | '/depute/$slug'
    | '/scrutin/$numero'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CommencerRoute: typeof CommencerRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DeputesRoute: typeof DeputesRoute
  Legislature16Route: typeof Legislature16Route
  RechercheRoute: typeof RechercheRoute
  ScrutinsRoute: typeof ScrutinsRoute
  ApiVisitsRoute: typeof ApiVisitsRoute
  DeputeSlugRoute: typeof DeputeSlugRoute
  ScrutinNumeroRoute: typeof ScrutinNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scrutins': {
      id: '/scrutins'
      path: '/scrutins'
      fullPath: '/scrutins'
      preLoaderRoute: typeof ScrutinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislature-16': {
      id: '/legislature-16'
      path: '/legislature-16'
      fullPath: '/legislature-16'
      preLoaderRoute: typeof Legislature16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputes': {
      id: '/deputes'
      path: '/deputes'
      fullPath: '/deputes'
      preLoaderRoute: typeof DeputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commencer': {
      id: '/commencer'
      path: '/commencer'
      fullPath: '/commencer'
      preLoaderRoute: typeof CommencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/scrutin/$numero': {
      id: '/scrutin/$numero'
      path: '/scrutin/$numero'
      fullPath: '/scrutin/$numero'
      preLoaderRoute: typeof ScrutinNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depute/$slug': {
      id: '/depute/$slug'
      path: '/depute/$slug'
      fullPath: '/depute/$slug'
      preLoaderRoute: typeof DeputeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CommencerRoute: CommencerRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DeputesRoute: DeputesRoute,
  Legislature16Route: Legislature16Route,
  RechercheRoute: RechercheRoute,
  ScrutinsRoute: ScrutinsRoute,
  ApiVisitsRoute: ApiVisitsRoute,
  DeputeSlugRoute: DeputeSlugRoute,
  ScrutinNumeroRoute: ScrutinNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
